### ISSUE TITLE
Switch to AGRC Vector Base Maps

### ISSUE THREAD

**Issue by stdavis** [agrc/recreate#33]
- [x] Generate vector tiles version of Terrain base map
- [x] Repoint this app to use it
- [x] Switch out mapbox static map (#26)

**Comment by brigsz** [comment]
If Zach handed you the vector tiles how long would it take you to hook them up for this app?

**Comment by stdavis** [comment]
Assuming that mapboxGL plays nice with the discover server, switching out the base maps should only be a few hours.

#26 Will be a bit more. We either need to make a custom service or just use a live map. I'm leaning towards the live map with I would guess 3-4 hours.

All of this could explode if there's issues with how discover serves vector tiles.

**Comment by stdavis** [comment]
Sent an email to Calvin asking if vector tiles ever made it to production on Giza and how to upload tiles.

**Comment by steveoh** [comment]
What tile are you going to toss up there?

**Comment by stdavis** [comment]
I have a preliminary version of Terrain from @ZachBeck.
![image](https://user-images.githubusercontent.com/1326248/38707022-c1feb52c-3e6c-11e8-8789-9cb5aeddf884.png)
![image](https://user-images.githubusercontent.com/1326248/38707026-c8481496-3e6c-11e8-8a01-6a6fc8244408.png)
![image](https://user-images.githubusercontent.com/1326248/38707029-cf7d6720-3e6c-11e8-96bc-e5a279c48180.png)
