### ISSUE TITLE
Point Clustering

### ISSUE THREAD

**Issue by stdavis** [agrc/recreate#51]
Not sure if the mapbox api even supports this or not. Tom requested it.

**Comment by brigsz** [comment]
Is this the functionality you speak of?  https://www.mapbox.com/ios-sdk/examples/clustering/

**Comment by stdavis** [comment]
Yes, that that's the wrong API. This project uses the React Native Mapbox GL API which wraps the one that you have referenced. It does appear that it supports clustering: https://github.com/mapbox/react-native-mapbox-gl/blob/release/6.1.1/docs/ShapeSource.md

**Comment by brigsz** [comment]
Yah, I did wonder when it said iOS.  Thanks
